# Generated by Django 5.0.1 on 2024-01-22 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('last_changed_on', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
    ]
